# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40f9937ba431a2445609f9eeccef927ec8f06255d98aae77f5fdc7171d2e4be9dee0b387a48747e059332e6d8c646a309e4ac867c5e1c1f2ce7159600bd8b4d9

test:
  secret_key_base: 60f75a6e3c35310922f3bb38ad7b7569a44c6844166f0c2da320feaefae04dec0e9d42f80e5c614800b09f60159abadab03917fd03ae877e5ced9c1ea444ef12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
